version: 0.2
phases:
  install:
    rutine-version:
      nodejs: latest
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run cy:parallel
  post_build:
    commands:
      - aws s3 sync allure-report s3://reporte-cypress
      - aws s3 cp --recursive --acl public-read s3://reporte-cypress s3://reporte-cypress --metadata-directive REPLACE